"""
Sabian Symbols — the 360 degree-symbols (Marc Edmund Jones / Elsie Wheeler set).
=================================================================================
Each of the 360 zodiacal degrees carries a symbolic image. For any planet or
angle at ecliptic longitude `lon`, the governing symbol is the one for the
WHOLE degree it occupies: a planet at 0°00'-0°59' Aries uses "Aries 1".

`sabian_for(longitude)` returns {sign, degree, symbol, label}.
"""

from __future__ import annotations
import math

SIGNS = [
    "Aries", "Taurus", "Gemini", "Cancer", "Leo", "Virgo",
    "Libra", "Scorpio", "Sagittarius", "Capricorn", "Aquarius", "Pisces",
]

SYMBOLS = [
    # Aries
    "A woman rises out of water, a seal rises and embraces her",
    "A comedian entertaining a group",
    "A cameo profile of a man in the outline of his country",
    "Two lovers strolling through a secluded walk",
    "A triangle with wings",
    "A square brightly lighted on one side",
    "A man successfully expressing himself in two realms at once",
    "A large woman's hat with streamers blown by an east wind",
    "A crystal gazer",
    "A teacher gives new symbolic forms to traditional images",
    "The ruler of a nation",
    "A flock of wild geese",
    "A bomb which failed to explode is now safely concealed",
    "A serpent coiling near a man and a woman",
    "An indian weaving a blanket",
    "Brownies dancing in the setting sun",
    "Two prim spinsters sitting together in silence",
    "An empty hammock",
    "A magic carpet hovers over a shabby countryside",
    "A young girl feeding birds in winter",
    "A pugilist entering the ring",
    "The gate to the garden of all fulfilled desires",
    "The gate opens to the garden of all fulfilled desires",
    "A woman in pastel colors carrying a heavy and valuable but veiled load",
    "A double promise reveals its inner and outer meanings",
    "A man possessed of more gifts than he can hold",
    "Through imagination a lost opportunity is regained",
    "A large audience confronts the performer who disappointed its ideals",
    "The music of the spheres",
    "A duck pond and its brood",
    # Taurus
    "A clear mountain stream flows steadily through a rocky field",
    "An electrical storm",
    "Steps up to a lawn blooming with clover",
    "The pot of gold at the end of the rainbow",
    "A widow at an open grave",
    "A bridge being built across a gorge",
    "A woman of Samaria comes to draw water from the well",
    "A sleigh without snow",
    "A Christmas tree decorated",
    "A red cross nurse",
    "A woman sprinkling flowers",
    "A young couple walk down main-street, window-shopping",
    "A man handling baggage",
    "On the beach, children play while shellfish grope at the edge of the water",
    "A man muffled up, with a rakish silk hat",
    "An old teacher fails to interest his pupils in traditional knowledge",
    "A symphony orchestra",
    "A woman airing an old bag through a sunny window",
    "A new continent rising out of the ocean",
    "Wisps of clouds, like wings, are streaming across the sky",
    "A finger pointing to a line in an open book",
    "A white dove flying over troubled waters",
    "A jewelry shop filled with the most magnificent jewels",
    "A mounted Indian with scalp locks",
    "A large well-kept public park",
    "A Spaniard serenading his senorita",
    "An old Indian woman selling beads",
    "A mature woman reawakened to romance",
    "A peacock parading on an ancient lawn",
    "A woman, past her 'change of life', experiences a new love",
    # Gemini
    "A glass-bottomed boat reveals under-sea wonders",
    "Santa Claus filling stockings furtively",
    "The garden of the Tuileries in Paris",
    "Holly and mistletoe bring Christmas spirit to a home",
    "A radical magazine, asking for action, displays a sensational front page",
    "Workmen drilling for oil",
    "An old-fashioned well",
    "Aroused strikers surround a factory",
    "A quiver filled with arrows",
    "An airplane performing a nose-dive",
    "Newly opened lands offer the pioneer new opportunities for experience",
    "A topsy saucily asserting herself",
    "A great musician at his piano",
    "Two people, living far apart, in telepathic communication",
    "Two Dutch children talking",
    "A woman activist in an emotional speech dramatizing her cause",
    "The head of a robust youth changes into that of a mature thinker",
    "Two Chinese men talking Chinese in a Western crowd",
    "A large archaic volume reveals a traditional wisdom",
    "A cafeteria with an abundance of choices",
    "A labor demonstration",
    "Dancing couples crowd the barn in a harvest festival",
    "Three fledglings in a nest high in a tree",
    "A modern cafeteria displays an abundance of food, milk in bottles",
    "A gardener trimming large palm trees",
    "Frost-covered trees against winter skies",
    "A young gypsy emerging from the woods gazes at far cities",
    "Society granting bankruptcy to him, a man leaves the court",
    "The first mockingbird of spring sings from the treetop",
    "A parade of bathing beauties before large beach crowds",
    # Cancer
    "On a ship the sailors lower an old flag and raise a new one",
    "A man on a magic carpet observes vast vistas below",
    "A man bundled in fur leads a shaggy deer",
    "A cat arguing with a mouse",
    "At a railroad crossing, an automobile is wrecked by a train",
    "Game birds feathering their nests",
    "Two fairies (nature spirits) dancing on a moonlit night",
    "A group of rabbits dressed in clothes and on parade",
    "A small, naked girl bends over a pond trying to catch a fish",
    "A large diamond in the first stages of the cutting process",
    "A clown caricaturing well-known personalities",
    "A Chinese woman nursing a baby whose aura reveals him to be the reincarnation of a great teacher",
    "One hand slightly flexed with a very prominent thumb",
    "A very old man facing a vast dark space to the northeast",
    "A group of people who have overeaten and enjoyed it",
    "A man studying a mandala in front of him, with the help of a very ancient book",
    "The unfoldment of multilevel potentialities issuing from an original germ",
    "A hen scratching for her chicks",
    "A priest performing a marriage ceremony",
    "Venetian gondoliers giving a serenade",
    "A prima donna singing",
    "A woman awaiting a sailboat, her lover, returns from the sea",
    "The meeting of a literary society",
    "A woman and two men castaways on a small island in the South Seas",
    "A will-full man is overshadowed by a descent of superior power",
    "A violent storm in a canyon filled with expensive homes",
    "A storm in a canyon",
    "An indian girl introduces her white lover to her assembled tribe",
    "A greek muse weighing new-born twins in golden scales",
    "A daughter of the American Revolution",
    # Leo
    "Under emotional stress, blood rushes to a man's head",
    "An epidemic of mumps",
    "A middle-aged woman, her long hair flowing over her shoulders, in a bygone romantic mood",
    "A formally dressed elderly man stands near trophies he brought back from a hunting expedition",
    "Rock formations tower over a deep canyon",
    "An old fashioned 'conservative' woman is confronted by an up-to-date girl",
    "The constellations of stars shine brilliantly in the night sky",
    "A communist activist spreading his revolutionary ideals",
    "Glass blowers shape beautiful vases with their controlled breathing",
    "Early morning dew sparkles as sunlight floods the field",
    "Children play on a swing hanging from the branches of a huge oak tree",
    "An evening lawn party of adults",
    "An old sea captain rocking on the porch of his cottage",
    "A human soul, in its eagerness for new experiences, seeks embodiment",
    "A pageant moving along a street packed with people",
    "Brilliant sunshine just after a storm",
    "A non-vested church choir sings religious hymns",
    "A chemist conducts an experiment for his students",
    "A houseboat party",
    "Zuni Indians perform a ritual to the sun",
    "Intoxicated chickens dizzily flap their wings trying to fly",
    "A carrier pigeon fulfilling its mission",
    "A bareback rider in a circus displays her dangerous skill",
    "Totally concentrated upon inner spiritual attainment, a man is sitting in a state of complete neglect of his body",
    "A large camel crossing a vast and forbidding desert",
    "After a heavy storm, a rainbow",
    "A daughter of the American Revolution",
    "Many little birds on the limb of a large tree",
    "A mermaid emerges from the ocean waves ready for rebirth in human form",
    "An unsealed letter",
    # Virgo
    "In a portrait, the best of a man's features and traits are idealized",
    "A large white cross-dominates the landscape",
    "Two guardian angels bringing protection",
    "Black and white children playing together happily",
    "A man becoming aware of nature spirits and normally unseen spiritual energies",
    "A merry-go-round",
    "A harem",
    "A girl takes her first dancing instruction",
    "A expressionist painter making a futuristic drawing",
    "Two heads looking out and beyond the shadows",
    "A boy molded in his mother's aspiration for him",
    "A bride with her veil snatched away",
    "A powerful statesman overcomes a state of political hysteria",
    "A family tree",
    "A fine lace ornamental handkerchief",
    "Children crowd around the orang-utang cage in a zoo",
    "A volcanic eruption",
    "Two girls playing with a Ouija board",
    "A swimming race",
    "A caravan of cars headed to the west coast",
    "A girls' basketball team",
    "A royal coat of arms enriched with precious stones",
    "A lion-tamer rushes fearlessly into the circus arena",
    "Mary and her white lamb",
    "A flag at half-mast in front of a public building",
    "A boy with a censer serves the priest near the altar",
    "A group of aristocratic ladies meet ceremonially at a court's function",
    "A bald-headed man who has seized power",
    "A man gaining secret knowledge from an ancient scroll he is reading",
    "A false call unheard in attention to immediate service",
    # Libra
    "A butterfly preserved and made perfect with a dart through it",
    "The light of the sixth race transmuted to the seventh",
    "The dawn of a new day reveals everything changed",
    "A group of young people sit in spiritual communion around a campfire",
    "A man revealing to his students the foundation of an inner knowledge upon which a 'new world' could be built",
    "A man watches his ideals taking a concrete form before his inner vision",
    "A woman feeding chickens and protecting them from the hawks",
    "A blazing fireplace in a deserted home",
    "Three old masters hanging in a special room in an art gallery",
    "A canoe approaching safety through dangerous waters",
    "A professor peering over his glasses at his students",
    "Miners are emerging from a deep coal mine",
    "Children blowing soap bubbles",
    "In the heat of noon, a man takes a siesta",
    "Circular paths",
    "After a storm, a boat landing stands in need of reconstruction",
    "A retired sea captain watches ships entering and leaving the harbor",
    "Two men placed under arrest",
    "A gang of robbers in hiding",
    "A Jewish rabbi performing his duties",
    "A crowd upon a beach",
    "A child giving birds a drink at a fountain",
    "Chanticleer's voice heralds sunrise",
    "A butterfly with the right wing more perfectly formed",
    "The sight of an autumn leaf brings to a pilgrim the sudden revelation of the mystery of life and death",
    "An eagle and a large white dove turning into each other",
    "An airplane sails, high in the clear sky",
    "A man in the midst of brightening influences",
    "Mankind's vast enduring effort to reach for knowledge transferable from generation to generation",
    "Three mounds of knowledge on a philosopher's head",
    # Scorpio
    "A sight-seeing bus filled with tourists",
    "A broken bottle and spilled perfume",
    "A house-raising party in a small village enlists the neighbors' cooperation",
    "A youth holding a lighted candle in a devotional ritual",
    "A massive, rocky shore resists the pounding of the sea",
    "A gold rush tears men away from their native soil",
    "Deep-sea divers",
    "The moon shining across a lake",
    "A dentist at work",
    "A fellowship supper reunites old comrades",
    "A drowning man is being rescued",
    "An official embassy ball",
    "An inventor performs a laboratory experiment",
    "Telephone linemen at work installing new connections",
    "Children playing around five mounds of sand",
    "A girl's face breaking into a smile",
    "A woman, filled with her own spirit, is the father of her own child",
    "A path through woods rich in autumn coloring",
    "A parrot listening and then talking, repeats a conversation he has overheard",
    "A woman drawing aside two dark curtains that closed the entrance to a sacred pathway",
    "Obeying his conscience, a soldier resists orders",
    "A hunter aiming his gun at a duck flying north",
    "A rabbit metamorphosed into a fairy (nature spirit)",
    "Crowds coming down the mountain to listen to one inspired man",
    "An X-ray photograph",
    "American Indians making camp in new territory",
    "A military band marches noisily on through the city streets",
    "The king of the fairies approaching his domain",
    "A halloween jester",
    "The Halls of Justice",
    # Sagittarius
    "Retired army veterans gather to reawaken old memories",
    "The ocean covered with whitecaps",
    "Two men playing chess",
    "A little child learning to walk",
    "An old owl up in a tree",
    "A game of cricket",
    "Cupid knocking at the door of a human heart",
    "Deep within the depths of the earth, new elements are being formed",
    "A mother leads her small child step by step up the stairs",
    "A theatrical representation of a golden-haired 'goddess of opportunity'",
    "The lamp of physical enlightenment at the left temple",
    "A flag that turns into an eagle that crows",
    "A widow's past is brought to light",
    "The great pyramid and the sphinx",
    "The ground hog looking for its shadow on ground-hog day",
    "Sea gulls fly around a ship in expectation of food",
    "An Easter sunrise service",
    "Tiny children in sunbonnets",
    "Pelicans, disturbed by the garbage of people, move their young to a new habitat",
    "In winter people cutting ice from a frozen pond, for summer use",
    "A child and a dog wearing borrowed eyeglasses",
    "A Chinese laundry",
    "Immigrants entering a new country",
    "A bluebird standing at the door of the house",
    "A chubby boy on a hobby-horse",
    "A flag-bearer in a battle",
    "The sculptor's vision is taking form",
    "A fat boy mowing the lawn",
    "A commander-in-chief silhouettes his features before the campaign",
    "The Pope blessing the faithful",
    # Capricorn
    "An Indian chief claims power from the assembled tribe",
    "Three stained-glass windows in a Gothic church, one damaged by war",
    "A human soul, in its eagerness for new experiences, seeks embodiment",
    "A group of people entering a large canoe for a journey by water",
    "Indians rowing a canoe and dancing a war dance",
    "Ten logs lie under an archway leading to darker woods",
    "A veiled prophet speaks, seized by the power of a god",
    "In a sun-lit home domesticated birds sing joyously",
    "An angel carrying a harp",
    "An albatross feeding from the hand of a sailor",
    "A large group of pheasant on a private estate",
    "A student of nature lecturing, revealing little-known aspects of life",
    "A fire worshipper meditates on the ultimate realities of existence",
    "An ancient bas-relief carved in granite remains a witness to a long-forgotten culture",
    "In a hospital, the children's ward is filled with toys",
    "School grounds filled with boys and girls in gymnasium suits",
    "A repressed woman finds a psychological release in nudism",
    "The union jack flies from a new British destroyer",
    "A child of about five carrying a huge shopping bag filled with groceries",
    "A hidden choir singing during a religious service",
    "A relay race",
    "A general accepting defeat gracefully",
    "Two awards for bravery in war",
    "A woman entering a convent",
    "A store filled with precious oriental rugs",
    "A nature spirit dancing in the mist of a waterfall",
    "A mountain pilgrimage",
    "A large aviary",
    "A secret business conference",
    "A secret meeting of men responsible for executive decisions in world affairs",
    # Aquarius
    "An old adobe mission in California",
    "An unexpected thunderstorm",
    "A deserter from the navy",
    "A Hindu healer glowing with a mystic healing power",
    "A council of ancestors is implementing the efforts of a young leader",
    "A performer of a mystery play",
    "A child born out of an eggshell",
    "Beautifully gowned wax figures on display",
    "A flag is seen turning into an eagle",
    "A popularity that proves to be fleeting",
    "During a silent hour, a man receives a new inspiration which may change his life",
    "People on a vast staircase, graduated upwards",
    "A barometer",
    "A train entering a tunnel",
    "Two lovebirds sitting on a fence and singing happily",
    "A big-business man at his desk",
    "A watchdog standing guard, protecting his master and his possessions",
    "A man's secret motives are being publicly unmasked",
    "A forest fire quenched",
    "A large white dove bearing a message",
    "A woman disappointed and disillusioned, courageously facing a seemingly empty life",
    "A rug placed on a floor for children to play on",
    "A big bear sitting down and waving all its paws",
    "A man turning his back on his passions teaches deep wisdom from his experience",
    "A butterfly emerging from a chrysalis",
    "A garage man testing a car's battery with a hydrometer",
    "An ancient pottery bowl filled with violets",
    "A tree felled and sawed to ensure a supply of wood for the winter",
    "A conservative, old-fashioned lady is confronted by a 'hippie' girl",
    "Deeply rooted in the past of a very ancient culture, a spiritual brotherhood in which many individual minds are merged into the glowing light of a unanimous consciousness is revealed to one who has emerged successfully from initiation",
    # Pisces
    "A crowded public marketplace",
    "A squirrel hiding from hunters",
    "A petrified forest",
    "Heavy car traffic on a narrow isthmus linking two seaside resorts",
    "A church bazaar",
    "A parade of army officers in full dress",
    "Illuminated by a shaft of light, a large cross lies on rocks surrounded by sea and mist",
    "A girl blowing a bugle",
    "A jockey spurs his horse, intent on outdistancing his rivals",
    "An aviator in the clouds",
    "Men traveling a narrow path, seeking illumination",
    "An examination of initiates in the sanctuary of an occult brotherhood",
    "A sword, used in many battles, is now in a museum",
    "A lady wrapped in fox fur",
    "An officer instructing his men before a simulated assault under a barrage of live shells",
    "In the quiet of his study a creative individual experiences a flow of inspiration",
    "An Easter promenade",
    "A gigantic tent with performances under a spotlight",
    "A master instructing his disciple",
    "A table set for an evening meal",
    "A little white lamb, a child and a Chinese servant",
    "A prophet bringing down the new law from Mount Sinai",
    "A materializing medium giving a séance",
    "An inhabited island",
    "The purging of the priesthood",
    "A new moon reveals that it's time for people to go ahead with their different projects",
    "A harvest moon illuminates the sky",
    "A fertile garden under the full moon",
    "A prism",
    "A majestic rock formation resembling a face is idealized by a boy who takes it as his ideal of greatness",
]


def sabian_for(longitude: float) -> dict:
    """Return the Sabian symbol governing the given ecliptic longitude."""
    lon = longitude % 360.0
    idx = int(math.floor(lon))
    sign_idx = idx // 30
    deg_in_sign = idx % 30
    symbol = SYMBOLS[idx] if idx < len(SYMBOLS) else "(symbol unavailable)"
    return {
        "sign": SIGNS[sign_idx],
        "degree": deg_in_sign + 1,
        "label": f"{SIGNS[sign_idx]} {deg_in_sign + 1}",
        "symbol": symbol,
    }


assert len(SYMBOLS) == 360, f"Expected 360 Sabian symbols, got {len(SYMBOLS)}"


if __name__ == "__main__":
    for lon in (0.5, 54.4, 191.2, 359.9):
        s = sabian_for(lon)
        print(f"{lon:7.2f} -> {s['label']}: {s['symbol']}")
